### ISSUE TITLE
Document config.module has been renamed in config.moduleFilter

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.qunitjs.com#100]
As per the [changelog](https://github.com/jquery/qunit/blob/master/History.md#1160--2014-12-03), in version 1.16.0 the property `module` was renamed in `moduleFilter`.

**Comment by jzaefferer** [comment]
Could catch, thanks. Could you do a PR for this?

**Comment by AurelioDeRosa** [comment]
Sure. Do you want to have a note about the old name or not?

**Comment by jzaefferer** [comment]
Yeah, that would be good.
