### ISSUE TITLE
Document QUnit.config.collapse

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.qunitjs.com#102]
See https://github.com/jquery/qunit/pull/780

@shivamdixit could you update the API docs for this change as well?

**Comment by shivamdixit** [comment]
Definitely, I will update them soon.

**Comment by shivamdixit** [comment]
@jzaefferer I have updated QUnit.config.reorder for https://github.com/jquery/qunit/pull/780. Do we need to document QUnit.config.collapse created at https://github.com/jquery/qunit/pull/769?

**Comment by jzaefferer** [comment]
Yes, a PR for `config.collapse` would be great as well.
