### ISSUE TITLE
Document missing QUnit.config properties

### ISSUE THREAD

**Issue by gibson042** [jquery/api.qunitjs.com#116]
Known missing from http://api.qunitjs.com/QUnit.config/ :
* `filter`
* `module` (which the documentation claims has been replaced by `moduleFilter` as of 1.16.0, but the code doesn't seem to reflect)
* `fixture`
* `maxDepth`
* `noglobals`
* `notrycatch`

NB: the above tries to leave out our (abusive) use of the same object for both internal and external properties, and therefore might misclassify some properties in either direction.

**Comment by jzaefferer** [comment]
The documentation can point out which of these properties we expect the user to set (in code, through web UI) and which they should never interact with (like `fixture`).
