### ISSUE TITLE
Rename branch to 'master'

### ISSUE THREAD

**Issue by Krinkle** [jquery/api.qunitjs.com#155]
Since we're using it for a full domain and the repo won't contain anything else, it probably makes more sense to use a master branch instead.

GitHub supports this in the settings:
<img width="549" alt="screen shot 2017-04-01 at 13 10 06" src="https://cloud.githubusercontent.com/assets/156867/24582069/8b210cac-16dc-11e7-8c3a-f2e1d6c57663.png">

It also has the benefit of allowing Travis CI to run, which right now it cannot because it internally ignores any gh-pages branch (but not @leobalter's `readme` branch for example).

<img width="513" alt="screen shot 2017-04-01 at 13 11 06" src="https://cloud.githubusercontent.com/assets/156867/24582077/c3630cc8-16dc-11e7-8b01-6850e43b0a0f.png">

**Comment by leobalter** [comment]
@Krinkle we actually need to freeze this repo.

I'll move it back to master as suggested but the current API docs are already at [qunitjs/qunit](https://github.com/qunitjs/qunit) in the docs folder.

**Comment by Krinkle** [comment]
Renamed for now. Also added note in the description pointing to <https://github.com/qunitjs/qunit/tree/master/docs>.
